"""scripts/factory-status.py — RFC 011 Phase 1's built-vs-needed report.

Hermetic: the "published index" is a file:// rpm-md fixture, so these tests
pin the classification and honesty rules without any network:

  * a catalog entry is BUILT if the index carries its name as a binary
    package OR as the source name behind one (the catalog speaks in source
    names; indexes list binaries);
  * duplicate catalog entries for one (name, target) count once;
  * targets without a readable index are REPORTED, never dropped;
  * provenance (revision, primary sha256) rides with every measurement.
"""
from __future__ import annotations

import gzip
import hashlib
import importlib.util
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location(
    "factory_status", ROOT / "scripts" / "factory-status.py"
)
fs = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(fs)

import sys  # noqa: E402

sys.path.insert(0, str(ROOT / "scripts"))
import published_index as pubidx  # noqa: E402

PRIMARY = """<?xml version="1.0"?>
<metadata xmlns="http://linux.duke.edu/metadata/common"
          xmlns:rpm="http://linux.duke.edu/metadata/rpm" packages="2">
  <package type="rpm">
    <name>cosmic-comp</name><arch>x86_64</arch>
    <version epoch="0" ver="1.0" rel="1"/>
    <format><rpm:sourcerpm>cosmic-comp-1.0-1.src.rpm</rpm:sourcerpm></format>
  </package>
  <package type="rpm">
    <name>xfconf-libs</name><arch>x86_64</arch>
    <version epoch="0" ver="4.20" rel="2"/>
    <format><rpm:sourcerpm>xfconf-4.20-2.src.rpm</rpm:sourcerpm></format>
  </package>
</metadata>
"""


def make_index(tmp_path: pathlib.Path) -> str:
    repodata = tmp_path / "repodata"
    repodata.mkdir(parents=True)
    blob = gzip.compress(PRIMARY.encode())
    (repodata / "primary.xml.gz").write_bytes(blob)
    sha = hashlib.sha256(blob).hexdigest()
    (repodata / "repomd.xml").write_text(
        f"""<?xml version="1.0"?>
<repomd xmlns="http://linux.duke.edu/metadata/repo">
  <revision>1755000000</revision>
  <data type="primary">
    <checksum type="sha256">{sha}</checksum>
    <location href="repodata/primary.xml.gz"/>
  </data>
</repomd>
"""
    )
    return tmp_path.as_uri() + "/"


def fixture_inputs(tmp_path):
    url = make_index(tmp_path / "repo")
    catalog = {
        "packages": [
            # BUILT by binary name.
            {"name": "cosmic-comp", "targets": ["el10"]},
            # BUILT by SOURCE name: the index only has xfconf-libs, whose
            # sourcerpm is xfconf — the catalog speaks in source names.
            {"name": "xfconf", "targets": ["el10"]},
            # NEEDED: nowhere in the index.
            {"name": "plasma-desktop", "targets": ["el10"]},
            # Duplicate family entry for the same (name, target): counts once.
            {"name": "cosmic-comp", "targets": ["el10"]},
            # Different target entirely — must not leak into el10.
            {"name": "waybar", "targets": ["debian"]},
        ]
    }
    factory = {
        "targets": {
            "el10": {
                "format": "rpm",
                "architectures": ["x86_64"],
                "published_index": {"x86_64": url},
            },
            "debian": {"format": "deb"},
        }
    }
    return catalog, factory


def test_classification_built_needed_and_source_names(tmp_path):
    catalog, factory = fixture_inputs(tmp_path)
    report = fs.measure(catalog, factory, tmp_path / "cache")
    data = report["targets"]["el10"]["x86_64"]
    assert data["built"] == ["cosmic-comp", "xfconf"]
    assert data["needed"] == ["plasma-desktop"]
    # Deduped: 4 el10 entries, 3 distinct names.
    assert data["catalog_entries"] == 3


def test_provenance_rides_with_the_measurement(tmp_path):
    catalog, factory = fixture_inputs(tmp_path)
    report = fs.measure(catalog, factory, tmp_path / "cache")
    indexes = report["targets"]["el10"]["x86_64"]["indexes"]
    assert len(indexes) == 1
    index = indexes[0]
    assert index["revision"] == "1755000000"
    assert len(index["primary_sha256"]) == 64
    assert index["package_names"] == 2


def test_unmeasured_targets_are_reported_not_dropped(tmp_path):
    catalog, factory = fixture_inputs(tmp_path)
    report = fs.measure(catalog, factory, tmp_path / "cache")
    assert "debian" in report["unmeasured_targets"]
    assert report["unmeasured_targets"]["debian"]["catalog_entries"] == 1
    rendered = fs.render(report)
    assert "Not yet measured" in rendered
    assert "debian" in rendered


def test_render_names_generation_and_counts(tmp_path):
    catalog, factory = fixture_inputs(tmp_path)
    report = fs.measure(catalog, factory, tmp_path / "cache")
    rendered = fs.render(report)
    assert "GENERATED by scripts/factory-status.py" in rendered
    assert "| x86_64 | 3 | 2 | 1 | 2 |" in rendered


def test_repo_manifests_pass_check_structure():
    """The real package-factory.yaml stays consistent with the tool's rules:
    every published_index target uses a readable format (rpm-md or flat
    apt), every arch is declared, every URL scheme is supported. Runs the
    same code path CI's drift check uses."""
    factory = fs.load_yaml(ROOT / "manifests" / "package-factory.yaml")
    measured = [t for t, spec in factory["targets"].items()
                if spec.get("published_index")]
    assert measured, "no target declares a published_index"
    for target_id in measured:
        spec = factory["targets"][target_id]
        assert spec["format"] in ("rpm", "deb")
        for arch, declared in spec["published_index"].items():
            assert arch in spec["architectures"], (target_id, arch)
            resolved = pubidx.normalise(declared)
            assert resolved, (target_id, arch, "declared but empty")
            for url in resolved:
                assert url.startswith("https://"), (target_id, url)
